package com.visionforge.controller;

import com.visionforge.dto.request.ImageGenerationRequest;
import com.visionforge.dto.response.ImageResponse;
import com.visionforge.entity.User;
import com.visionforge.service.ImageService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * ImageController — REST controller for AI image generation and management.
 *
 * All endpoints require a valid JWT token (enforced by SecurityConfig +
 * JwtAuthenticationFilter). Spring Security places the authenticated User
 * into the SecurityContext; @AuthenticationPrincipal extracts it for us.
 *
 * Endpoints:
 *  POST   /api/images/generate     → Generate a new image from a prompt
 *  GET    /api/images/my-images    → List all images for the current user
 *  DELETE /api/images/{id}         → Delete an image (owner only)
 *
 * The controller is intentionally thin:
 *  - Validates the request  (@Valid)
 *  - Extracts the principal (@AuthenticationPrincipal)
 *  - Delegates to ImageService
 *  - Returns the ResponseEntity
 * No business logic lives here.
 */
@Slf4j
@RestController
@RequestMapping("/api/images")
@RequiredArgsConstructor
@Tag(name = "Image Generation", description = "AI image generation and management endpoints")
@SecurityRequirement(name = "bearerAuth")
public class ImageController {

    private final ImageService imageService;

    // ── POST /api/images/generate ─────────────────────────────────────────────

    /**
     * Generate a new AI image from a text prompt.
     *
     * This is the core Phase 3 endpoint. The request body is validated by
     * @Valid before the method is invoked — invalid prompts never reach the service.
     *
     * Expected processing time: 10–120 seconds (HF model cold-start + inference).
     * Returns HTTP 201 Created on success with the full ImageResponse body.
     *
     * @param request     validated generation parameters
     * @param currentUser the authenticated user (injected from SecurityContext)
     * @return 201 Created with ImageResponse, or error from GlobalExceptionHandler
     */
    @PostMapping("/generate")
    @Operation(
        summary     = "Generate AI image",
        description = "Generate a new image using an AI model. Consumes 1 credit. " +
                      "Processing may take 10-120 seconds depending on model load."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "201", description = "Image generated successfully"),
        @ApiResponse(responseCode = "400", description = "Invalid request (blank prompt, bad parameters)"),
        @ApiResponse(responseCode = "401", description = "JWT token missing or expired"),
        @ApiResponse(responseCode = "402", description = "No credits remaining"),
        @ApiResponse(responseCode = "502", description = "AI provider failed to generate the image")
    })
    public ResponseEntity<ImageResponse> generateImage(
            @Valid @RequestBody ImageGenerationRequest request,
            @AuthenticationPrincipal User currentUser) {

        log.info("[ImageController] POST /generate — user={} prompt='{}'",
                currentUser.getEmail(), truncate(request.getPrompt(), 60));

        ImageResponse response = imageService.generateImage(request, currentUser);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    // ── GET /api/images/my-images ─────────────────────────────────────────────

    /**
     * Retrieve all images belonging to the authenticated user.
     * Returns newest-first. Includes FAILED attempts so users can see
     * why a generation failed.
     *
     * @param currentUser the authenticated user
     * @return 200 OK with list of ImageResponse (may be empty)
     */
    @GetMapping("/my-images")
    @Operation(
        summary     = "Get my images",
        description = "Retrieve all images generated by the authenticated user, newest first."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "Images retrieved successfully"),
        @ApiResponse(responseCode = "401", description = "JWT token missing or expired")
    })
    public ResponseEntity<List<ImageResponse>> getMyImages(
            @AuthenticationPrincipal User currentUser) {

        log.debug("[ImageController] GET /my-images — user={}", currentUser.getEmail());

        List<ImageResponse> images = imageService.getMyImages(currentUser);
        return ResponseEntity.ok(images);
    }

    // ── DELETE /api/images/{id} ───────────────────────────────────────────────

    /**
     * Delete an image by ID.
     * Only the owner of the image can perform this operation.
     * Returns 204 No Content on success (no response body).
     *
     * @param id          the image ID from the URL path
     * @param currentUser the authenticated user attempting the deletion
     * @return 204 No Content, or 404/403 from GlobalExceptionHandler
     */
    @DeleteMapping("/{id}")
    @Operation(
        summary     = "Delete image",
        description = "Delete an image by ID. Only the image owner can perform this operation."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "204", description = "Image deleted successfully"),
        @ApiResponse(responseCode = "401", description = "JWT token missing or expired"),
        @ApiResponse(responseCode = "403", description = "You are not the owner of this image"),
        @ApiResponse(responseCode = "404", description = "Image not found")
    })
    public ResponseEntity<Void> deleteImage(
            @PathVariable Long id,
            @AuthenticationPrincipal User currentUser) {

        log.info("[ImageController] DELETE /{} — user={}", id, currentUser.getEmail());

        imageService.deleteImage(id, currentUser);
        return ResponseEntity.noContent().build();
    }

    // ── Utility ───────────────────────────────────────────────────────────────

    private String truncate(String s, int maxLen) {
        if (s == null) return "";
        return s.length() <= maxLen ? s : s.substring(0, maxLen) + "...";
    }
}
